x-nfcompose-credentials-env: &x-nfcompose-credentials-env
  NF_COMPOSE_USER: "admin"
  NF_COMPOSE_PASSWORD: "admin"
  NF_COMPOSE_URL: "http://skipper.internal.local:8000"

services:
  process:
    image: docker.neuroforge.de/skipper/functions/process:latest
    build:
      context: ./functions/process
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: ./functions/process
          target: /app
          ignore:
            - venv
    environment:
      <<: *x-nfcompose-credentials-env
    networks:
      nfcompose_consumers:
        aliases:
          - process.local
        
  httpendpoint:
    image: docker.neuroforge.de/skipper/functions/process:latest
    build:
      context: ./functions/httpendpoint
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: ./functions/httpendpoint
          target: /app
          ignore:
            - venv
    environment:
      <<: *x-nfcompose-credentials-env
    networks:
      nfcompose:
        aliases:
          - httpendpoint.local

networks:
  nfcompose:
    name: "nf-compose_nfcompose"
    external: true
  nfcompose_consumers:
    name: "nf-compose_nfcompose_consumers"
    external: true
